# Generated by Django 3.1.7 on 2021-04-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('core', '0003_auto_20210331_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='plans',
            field=models.ManyToManyField(to='plans.Plan'),
        ),
        migrations.DeleteModel(
            name='RegularPlan',
        ),
    ]
