# Generated by Django 3.1.7 on 2021-04-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('core', '0005_auto_20210402_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='plans',
            field=models.ManyToManyField(blank=True, to='plans.Plan'),
        ),
    ]
