# Generated by Django 3.1.7 on 2021-04-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('core', '0006_auto_20210402_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='plans',
            field=models.ManyToManyField(to='plans.Plan'),
        ),
    ]
