# Generated by Django 3.1.7 on 2021-04-02 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('tar_included', models.BooleanField()),
                ('subscription', models.FloatField()),
                ('cycle', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('type', models.CharField(choices=[('bi-time', 'Bi-time'), ('tri-time', 'Tri-time'), ('simple', 'Simple')], max_length=10)),
                ('offer_iva', models.BooleanField()),
                ('off_peak_price', models.FloatField()),
                ('peak_price', models.FloatField()),
                ('unit', models.CharField(choices=[('kwh', 'kwh'), ('min', 'min')], max_length=3)),
                ('valid', models.BooleanField()),
                ('publish', models.BooleanField()),
                ('vat', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
